import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

public final class GenerateRunSpain14 {
    private static final int SOURCE_LEVEL = 13;
    private static final double MIN_LONGITUDE = -9.5;
    private static final double MAX_LONGITUDE = 4.5;
    private static final double MIN_LATITUDE = 36.0;
    private static final double MAX_LATITUDE = 44.0;
    private static final double REGION_SIZE = 0.5;
    private static final Path TOPLEVEL_DIRECTORY =
        Path.of("/samples/datasets/googleEarth/toplevel");
    private static final Path SCRIPT_OUTPUT = Path.of("scripts/runSpain14.sh");

    private record Tile(String quadkey, double west, double east, double south, double north) {}

    private record Region(double latitude, double longitude, int intersectingTiles) {}

    public static void main(String[] args) throws Exception {
        List<Tile> tiles = loadLevelTiles();
        List<Region> regions = coveredRegions(tiles);
        writeScript(regions, tiles.size());
        System.out.printf(
            Locale.ROOT,
            "Generated %s with %d covered 0.5-degree regions from %d level-%d tiles.%n",
            SCRIPT_OUTPUT,
            regions.size(),
            tiles.size(),
            SOURCE_LEVEL
        );
    }

    private static List<Tile> loadLevelTiles() throws IOException {
        Set<String> quadkeys = new LinkedHashSet<>();
        try (var paths = Files.walk(TOPLEVEL_DIRECTORY)) {
            paths.filter(Files::isRegularFile)
                .map(path -> path.getFileName().toString())
                .filter(name -> name.matches("0[0-3]{" + SOURCE_LEVEL + "}\\.png"))
                .map(name -> name.substring(0, name.length() - ".png".length()))
                .forEach(quadkeys::add);
        }
        List<Tile> tiles = new ArrayList<>(quadkeys.size());
        for (String quadkey : quadkeys) {
            tiles.add(decode(quadkey));
        }
        return tiles;
    }

    private static Tile decode(String quadkey) {
        int column = 0;
        int southRow = 0;
        for (int index = 1; index < quadkey.length(); index++) {
            int quadrant = quadkey.charAt(index) - '0';
            column = (column << 1) | ((quadrant == 1 || quadrant == 2) ? 1 : 0);
            southRow = (southRow << 1) | ((quadrant == 2 || quadrant == 3) ? 1 : 0);
        }
        int side = 1 << SOURCE_LEVEL;
        double span = 360.0 / side;
        double west = -180.0 + column * span;
        double south = -180.0 + southRow * span;
        return new Tile(quadkey, west, west + span, south, south + span);
    }

    private static List<Region> coveredRegions(List<Tile> tiles) {
        List<Region> regions = new ArrayList<>();
        for (double longitude = MIN_LONGITUDE; longitude < MAX_LONGITUDE; longitude += REGION_SIZE) {
            for (double latitude = MIN_LATITUDE; latitude < MAX_LATITUDE; latitude += REGION_SIZE) {
                int count = 0;
                for (Tile tile : tiles) {
                    if (intersects(tile, latitude, longitude)) {
                        count++;
                    }
                }
                if (count > 0) {
                    regions.add(new Region(latitude, longitude, count));
                }
            }
        }
        return regions;
    }

    private static boolean intersects(Tile tile, double latitude, double longitude) {
        return tile.east() > longitude
            && tile.west() < longitude + REGION_SIZE
            && tile.north() > latitude
            && tile.south() < latitude + REGION_SIZE;
    }

    private static void writeScript(List<Region> regions, int sourceTileCount) throws IOException {
        try (PrintWriter writer = new PrintWriter(
            Files.newBufferedWriter(SCRIPT_OUTPUT, StandardCharsets.UTF_8)
        )) {
            writer.println("#!/usr/bin/env bash");
            writer.println();
            writer.println("set -Eeuo pipefail");
            writer.println();
            writer.println("readonly PROJECT_DIR=\"/paradigmas/master/algoritmos_basicos_3d/googleEarthApiTrace\"");
            writer.println("readonly PATH_PLANNER_DIR=\"$PROJECT_DIR/11_pathPlanner\"");
            writer.println("readonly MY_PLACES_DIR=\"$HOME/.googleearth\"");
            writer.println("readonly GOOGLE_EARTH_CLOSE_FAILURE='[SESSION] FAILURE: 13_googleEarthController reported: [ERROR] Google Earth did not close after File, UP, ENTER and PID fallback.'");
            writer.println();
            writer.println("# Generated by scripts/GenerateRunSpain14.java.");
            writer.printf(
                Locale.ROOT,
                "# Selected %d regions intersecting %d level-%d tiles in lat=[%.1f,%.1f), lon=[%.1f,%.1f).%n",
                regions.size(),
                sourceTileCount,
                SOURCE_LEVEL,
                MIN_LATITUDE,
                MAX_LATITUDE,
                MIN_LONGITUDE,
                MAX_LONGITUDE
            );
            writeValues(writer, "LATS", MIN_LATITUDE, MAX_LATITUDE);
            writeValues(writer, "LONS", MIN_LONGITUDE, MAX_LONGITUDE);
            writer.println();
            writer.println("should_download() {");
            writer.println("    case \"$1,$2\" in");
            for (int index = 0; index < regions.size(); index++) {
                Region region = regions.get(index);
                if (index % 6 == 0) {
                    writer.print("        ");
                }
                writer.printf(Locale.ROOT, "\"%.1f,%.1f\"", region.latitude(), region.longitude());
                if (index + 1 == regions.size()) {
                    writer.println(")");
                }
                else {
                    writer.print("|");
                    if (index % 6 == 5) {
                        writer.println("\\");
                    }
                }
            }
            writer.println("            return 0");
            writer.println("            ;;");
            writer.println("        *)");
            writer.println("            return 1");
            writer.println("            ;;");
            writer.println("    esac");
            writer.println("}");
            writer.println();
            writer.println("handle_google_earth_close_failure() {");
            writer.println("    local lat=\"$1\"");
            writer.println("    local lon=\"$2\"");
            writer.println("    local status=\"$3\"");
            writer.println("    local run_log=\"$4\"");
            writer.println();
            writer.println("    if ! grep -Fq \"$GOOGLE_EARTH_CLOSE_FAILURE\" \"$run_log\"; then");
            writer.println("        return 1");
            writer.println("    fi");
            writer.println();
            writer.println("    printf '[runSpain14][WARN] Ignoring recoverable Google Earth close failure at lat=%s lon=%s (status=%s).\\n' \\");
            writer.println("        \"$lat\" \"$lon\" \"$status\" >&2");
            writer.println("    if ! pkill -9 google-earth; then");
            writer.println("        printf '[runSpain14][WARN] pkill -9 google-earth did not terminate any process.\\n' >&2");
            writer.println("    fi");
            writer.println("    return 0");
            writer.println("}");
            writer.println();
            writer.println("for LON in \"${LONS[@]}\"; do");
            writer.println("    for LAT in \"${LATS[@]}\"; do");
            writer.println("        if ! should_download \"$LAT\" \"$LON\"; then");
            writer.println("            continue");
            writer.println("        fi");
            writer.println();
            writer.println("        cp -- \"$MY_PLACES_DIR/myplaces.kml.bak\" \"$MY_PLACES_DIR/myplaces.kml\"");
            writer.println();
            writer.println("        cd \"$PATH_PLANNER_DIR\"");
            writer.println("        ./run.sh zigzag \"$LAT\" \"$LON\" 10000 200 6000 0.5 0.5");
            writer.println();
            writer.println("        cd \"$PROJECT_DIR\"");
            writer.println("        pipeline_tmp_dir=\"${PIPELINE_TMP_DIR:-/media/ramdisk}\"");
            writer.println("        mkdir -p \"$pipeline_tmp_dir\"");
            writer.println("        run_log=\"$(mktemp \"$pipeline_tmp_dir/runSpain14.runFullProcess.XXXXXX\")\"");
            writer.println("        if ./scripts/runFullProcess.sh \\");
            writer.println("            --route-command \"./run.sh zigzag $LAT $LON 10000 200 6000 0.5 0.5\" \\");
            writer.println("            > >(tee \"$run_log\") 2>&1; then");
            writer.println("            rm -f -- \"$run_log\"");
            writer.println("        else");
            writer.println("            status=$?");
            writer.println("            if handle_google_earth_close_failure \"$LAT\" \"$LON\" \"$status\" \"$run_log\"; then");
            writer.println("                rm -f -- \"$run_log\"");
            writer.println("                continue");
            writer.println("            fi");
            writer.println("            rm -f -- \"$run_log\"");
            writer.println("            printf '[runSpain14][ERROR] Cycle failed at lat=%s lon=%s (status=%d). Stopping.\\n' \\");
            writer.println("                \"$LAT\" \"$LON\" \"$status\" >&2");
            writer.println("            exit \"$status\"");
            writer.println("        fi");
            writer.println("    done");
            writer.println("done");
        }
        SCRIPT_OUTPUT.toFile().setExecutable(true, false);
    }

    private static void writeValues(PrintWriter writer, String name, double min, double max) {
        writer.printf("readonly %s=(%n", name);
        for (double value = min; value < max; value += REGION_SIZE) {
            writer.printf(Locale.ROOT, "    \"%.1f\"%n", value);
        }
        writer.println(")");
    }
}
